-- Seed da tabela Modalidades (Compêndio de Atividades Físicas).
-- Gerado a partir de "SELECT * FROM "Modalidades"" no banco local (ronu_db em
-- localhost), em 2026-09-22 — não existia nenhum script versionado até então.
-- "Id" é serial (GENERATED BY DEFAULT AS IDENTITY), por isso é omitido aqui
-- de propósito: nenhum outro código no projeto depende de um valor fixo de
-- Id de modalidade, então deixamos o banco gerar.

INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Jiu-jitsu', 10.3);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Muay Thai', 10.3);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Boxe', 12.3);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Musculação', 5.0);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Futebol', 10.0);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Basquete', 8.0);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Natação', 7.0);
