-- Seed da tabela Modalidades (Compêndio de Atividades Físicas 2024 para adultos,
-- https://pacompendium.com — valores conferidos no site em 2026-10-03).
-- Criado a partir de "SELECT * FROM "Modalidades"" no banco local em 2026-09-22;
-- os METs foram trocados pelos do Compêndio 2024 em 2026-10-03 (migration
-- AtualizaMetsCompendio2024). A fonte dos valores no código é
-- src/Ronu.Api/Data/MetsCompendio2024.cs — mudou lá, muda aqui.
-- "Id" é serial (GENERATED BY DEFAULT AS IDENTITY), por isso é omitido aqui
-- de propósito: nenhum outro código no projeto depende de um valor fixo de
-- Id de modalidade, então deixamos o banco gerar.
--
-- MET bruto (inclui o repouso); o desconto de 1 MET é feito no cálculo
-- (CalculadoraGastoCalorico). Critério: o código que descreve uma sessão
-- típica de treino, não uma luta nem uma competição.
--
-- Aula de luta = composição de dois códigos, pelo tempo de cada bloco.
-- PREMISSA (não vem do Compêndio): 50% do tempo em aquecimento/técnica e 50%
-- em rola/sparring (MetsCompendio2024.FracaoTempoBlocoIntenso).
--   Jiu-jitsu e Muay Thai = 0,5 × 5,3 (15425, "Martial Arts, different types,
--     slower pace, novice performers, practice") + 0,5 × 10,3 (15430, "Martial
--     Arts, different types, moderate pace (e.g., judo, jujitsu, karate, kick
--     boxing, tae kwon do, tai-bo, Muay Thai boxing)") = 7,8
--   Boxe = 0,5 × 5,8 (15110, "Boxing, punching bag") + 0,5 × 7,8 (15120,
--     "Boxing, sparring") = 6,8
-- Demais (um código cada):
--   Musculação 3,5 (02054, "Resistance (weight) training, multiple exercises,
--     8-15 reps at varied resistance")
--   Futebol 7,0 (15610, "Soccer, casual, general (Taylor Code 540)")
--   Basquete 7,5 (15055, "Basketball, general")
--   Natação 5,8 (18240, "Swimming laps, freestyle, slow, recreational")

INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Jiu-jitsu', 7.8);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Muay Thai', 7.8);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Boxe', 6.8);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Musculação', 3.5);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Futebol', 7.0);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Basquete', 7.5);
INSERT INTO "Modalidades" ("Nome", "MetReferencia") VALUES ('Natação', 5.8);
